name: Publish_Release

on:
  push:
    tags:
      - "v*"

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: install wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: export game
        id: export
        uses: firebelley/godot-export@v5.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_export_templates.tpz
          relative_project_path: ./project # build the standard project
          relative_export_path: ./project/__build # move export output to this directory relative to git root
          archive_output: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
          use_godot_3: true

      - name: Fetch tags
        run: git fetch --tags --force # we --force due to something odd going on with git fetch conflicting with the local vs remote tag. I did checks to ensure that the commits are correct. see commit message

      - name: determine previous tag and save current tag
        id: get_previous_tag
        run: |
          git tag --sort=-committerdate | grep -B 1 "${{ github.ref_name }}"
          PREVIOUS_TAG=$(git tag --sort=-committerdate | grep -B 1 "${{ github.ref_name }}" | head -n 1)
          echo "$PREVIOUS_TAG" > previous_tag.txt
          echo "${{ github.ref_name }}" > buildnumber.txt

      - name: Upload txt files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: previous-tag-and-current-build
          path: |
            previous_tag.txt
            buildnumber.txt

      - name: generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(cat previous_tag.txt)
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "No previous tag found, skipping changelog generation."
          else
            echo "List of commits since: $PREVIOUS_TAG"
            COMMIT_HASHES=$(git rev-list --reverse --since="$PREVIOUS_TAG" HEAD)
            for commit_hash in $COMMIT_HASHES; do
              commit_msg=$(git log --format=%s -n 1 $commit_hash)
              echo "- $commit_msg"
            done > changelog2.txt
            cat changelog.txt # Debug: Print contents of changelog.txt
          fi

          
      - name: create release
        uses: ncipollo/release-action@v1.11.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*, changelog.txt, buildnumber.txt # Comma-separated list of artifacts
          draft: false
