name: Deploy_to_Itch

env:
  BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
    
on:
  workflow_run:
    workflows: ["Publish_Release"]
    types:
      - completed
      - released
      - published
      - prereleased

jobs:
  publish-html:
    runs-on: ubuntu-latest

    steps:
      - name: Download buildnumber.txt from latest release
        id: download_buildnumber
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: buildnumber.txt
          repo: boylecraft/cloudy_mountain
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Artifacts in Job 1
        run: |
          CURRENT_VERSION=$(cat buildnumber.txt)
          echo "Current version in Job 1: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Download the game from the latest release
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: HTML5.zip
          repo: boylecraft/godot-export-template
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and configure Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Unzip the game
        run: |
          mkdir godot-export-html5
          unzip HTML5.zip -d godot-export-html5

      - name: Push to itch.io
        run: |
          echo "Current Veresion = $CURRENT_VERSION"
          ./butler push godot-export-html5 jmbjr/godot-export:html5 --userversion=$CURRENT_VERSION

  publish-win:
    runs-on: ubuntu-latest

    steps:
      - name: Download buildnumber.txt from latest release
        id: download_buildnumber
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: buildnumber.txt
          repo: boylecraft/cloudy_mountain
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Use Artifacts in Job 2
        run: |
          CURRENT_VERSION=$(cat ./buildnumber.txt)
          echo "Current version in Job 2: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Download the game from the latest release
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: win.zip
          repo: boylecraft/godot-export-template
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and configure Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Unzip the game
        run: |
          mkdir godot-export-win
          unzip win.zip -d godot-export-win

      - name: Push to itch.io
        run: |
          echo "Current Veresion = $CURRENT_VERSION"
          ./butler push godot-export-win jmbjr/godot-export:windows --userversion=$CURRENT_VERSION

  publish-mac:
    runs-on: ubuntu-latest

    steps:

      - name: Download buildnumber.txt from latest release
        id: download_buildnumber
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: buildnumber.txt
          repo: boylecraft/cloudy_mountain
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Artifacts in Job 3
        run: |
          CURRENT_VERSION=$(cat buildnumber.txt)
          echo "Current version in Job 3: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Download the game from the latest release
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: osx.zip
          repo: boylecraft/godot-export-template
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and configure Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Unzip the game
        run: |
          mkdir godot-export-osx
          unzip osx.zip -d godot-export-osx

      - name: Push to itch.io
        run: |
          echo "Current Veresion = $CURRENT_VERSION"
          ./butler push godot-export-osx jmbjr/godot-export:mac_osx --userversion=$CURRENT_VERSION
          
  publish-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Download buildnumber.txt from latest release
        id: download_buildnumber
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: buildnumber.txt
          repo: boylecraft/cloudy_mountain
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Artifacts in Job 4
        run: |
          CURRENT_VERSION=$(cat buildnumber.txt)
          echo "Current version in Job 4: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          
      - name: Download the game from the latest release
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: LinuxX11.zip
          repo: boylecraft/godot-export-template
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and configure Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Unzip the game
        run: |
          mkdir godot-export-linux
          unzip LinuxX11.zip -d godot-export-linux

      - name: Push to itch.io
        run: |
          echo "Current Veresion = $CURRENT_VERSION"
          ./butler push godot-export-linux jmbjr/godot-export:linux --userversion=$CURRENT_VERSION