name: Deploy_to_Itch

env:
  BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
    
on:
  workflow_run:
    workflows: ["Publish_Release"]
    types:
      - completed
      - released
      - published
      - prereleased

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download the game from the latest release
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: win.zip
          repo: boylecraft/godot-export-template
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and configure Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Unzip the game
        run: |
          mkdir godot-export-win
          unzip win.zip -d godot-export-win

      - name: Push to itch.io
        run: |
          ./butler push godot-export-win jmbjr/godot-export:windows
